/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AWFPresaleInterface extends Interface {
    getFunction(nameOrSignature: "AWF_DECIMALS" | "STAGE1_LIMIT" | "STAGE1_PRICE" | "STAGE2_LIMIT" | "STAGE2_PRICE" | "STAGE3_LIMIT" | "STAGE3_PRICE" | "awf" | "buyWithUSDC" | "buyWithUSDT" | "currentPrice" | "currentStage" | "owner" | "renounceOwnership" | "saleActive" | "setSaleActive" | "totalSold" | "transferOwnership" | "usdc" | "usdt" | "withdrawAllToken" | "withdrawToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "SaleStatusChanged" | "TokensPurchased" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'AWF_DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE1_LIMIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE1_PRICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE2_LIMIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE2_PRICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE3_LIMIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE3_PRICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'awf', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyWithUSDC', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyWithUSDT', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'currentPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentStage', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'saleActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'setSaleActive', values: [boolean]): string;
encodeFunctionData(functionFragment: 'totalSold', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdt', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawAllToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawToken', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'AWF_DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE1_LIMIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE1_PRICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE2_LIMIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE2_PRICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE3_LIMIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE3_PRICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'awf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyWithUSDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyWithUSDT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentStage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saleActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSaleActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawAllToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawToken', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SaleStatusChangedEvent {
      export type InputTuple = [active: boolean];
      export type OutputTuple = [active: boolean];
      export interface OutputObject {active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, paymentToken: AddressLike, paymentAmount: BigNumberish, awfAmount: BigNumberish, stage: BigNumberish];
      export type OutputTuple = [buyer: string, paymentToken: string, paymentAmount: bigint, awfAmount: bigint, stage: bigint];
      export interface OutputObject {buyer: string, paymentToken: string, paymentAmount: bigint, awfAmount: bigint, stage: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [token: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, to: string, amount: bigint];
      export interface OutputObject {token: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AWFPresale extends BaseContract {
    
    connect(runner?: ContractRunner | null): AWFPresale;
    waitForDeployment(): Promise<this>;

    interface: AWFPresaleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    AWF_DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAGE1_LIMIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAGE1_PRICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAGE2_LIMIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAGE2_PRICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAGE3_LIMIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAGE3_PRICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    awf: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buyWithUSDC: TypedContractMethod<
      [paymentAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buyWithUSDT: TypedContractMethod<
      [paymentAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    currentPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    currentStage: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    saleActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setSaleActive: TypedContractMethod<
      [active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    totalSold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawAllToken: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawToken: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'AWF_DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE1_LIMIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE1_PRICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE2_LIMIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE2_PRICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE3_LIMIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE3_PRICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'awf'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyWithUSDC'): TypedContractMethod<
      [paymentAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyWithUSDT'): TypedContractMethod<
      [paymentAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentStage'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'saleActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setSaleActive'): TypedContractMethod<
      [active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalSold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawAllToken'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawToken'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'SaleStatusChanged'): TypedContractEvent<SaleStatusChangedEvent.InputTuple, SaleStatusChangedEvent.OutputTuple, SaleStatusChangedEvent.OutputObject>;
getEvent(key: 'TokensPurchased'): TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'SaleStatusChanged(bool)': TypedContractEvent<SaleStatusChangedEvent.InputTuple, SaleStatusChangedEvent.OutputTuple, SaleStatusChangedEvent.OutputObject>;
      SaleStatusChanged: TypedContractEvent<SaleStatusChangedEvent.InputTuple, SaleStatusChangedEvent.OutputTuple, SaleStatusChangedEvent.OutputObject>;
    

      'TokensPurchased(address,address,uint256,uint256,uint256)': TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
      TokensPurchased: TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
    

      'Withdrawn(address,address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }